image: "gradle:5.5.1-jdk12"

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - "export GRADLE_USER_HOME=`pwd`/.gradle"

stages:
  - "build"
  - "test"
  - "release"

build:
  stage: "build"
  tags:
    - "gradle"
  script: "su gradle -c 'gradle --build-cache assemble'"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: "push"
    paths:
      - "build"
      - ".gradle"

test:
  stage: "test"
  tags:
    - "gradle"
  script: "su gradle -c 'gradle check'"
  artifacts:
    reports:
      junit: "build/reports/integTestRunnerJunit/TEST-*.xml"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: "pull"
    paths:
      - "build"
      - ".gradle"

release:
  only:
    - "5.x"
    - "6.x"
    - "master"
  stage: "release"
  tags:
    - "gradle"
  script: "su gradle -c 'gradle release'"
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: "pull"
    paths:
      - "build"
      - ".gradle"
